-- Migration: Create messages table
-- Description: Core messages table for chat functionality with support for replies and message types

-- Message types enum for different kinds of system and user messages
CREATE TYPE message_type AS ENUM (
    'default',           -- Regular user message
    'recipient_add',     -- User added to group DM
    'recipient_remove',  -- User removed from group DM
    'call',              -- Voice/video call started
    'channel_name_change',
    'channel_icon_change',
    'channel_pinned_message',
    'guild_member_join', -- Welcome message when user joins server
    'reply'              -- Reply to another message
);

-- Messages table
-- Note: id is BIGINT (Snowflake ID) generated by application layer
CREATE TABLE messages (
    id BIGINT PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    message_type message_type NOT NULL DEFAULT 'default',
    reply_to_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    edited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ensure content is not empty for default messages
    CONSTRAINT messages_content_length CHECK (
        message_type != 'default' OR char_length(content) > 0
    ),
    -- Ensure content doesn't exceed Discord-like limits (4000 chars)
    CONSTRAINT messages_content_max_length CHECK (
        char_length(content) <= 4000
    )
);

-- Critical index for message retrieval (most common query pattern)
-- Fetching messages in a channel ordered by time (cursor-based pagination)
CREATE INDEX idx_messages_channel_created ON messages(channel_id, created_at DESC);

-- Index for fetching user's message history
CREATE INDEX idx_messages_author_id ON messages(author_id);

-- Partial index for reply lookups (only where reply exists)
CREATE INDEX idx_messages_reply_to ON messages(reply_to_id)
    WHERE reply_to_id IS NOT NULL;

-- Partial index for pinned messages (commonly filtered)
CREATE INDEX idx_messages_pinned ON messages(channel_id, created_at DESC)
    WHERE pinned = TRUE;

-- BRIN index for time-based range queries on large tables
-- More space-efficient than B-tree for time-series data
CREATE INDEX idx_messages_created_at_brin ON messages
    USING BRIN (created_at) WITH (pages_per_range = 128);

COMMENT ON TABLE messages IS 'Core messages table storing all chat messages';
COMMENT ON COLUMN messages.id IS 'Snowflake ID generated by application';
COMMENT ON COLUMN messages.content IS 'Message content, max 4000 characters';
COMMENT ON COLUMN messages.reply_to_id IS 'Reference to parent message for replies';
COMMENT ON COLUMN messages.edited_at IS 'Timestamp of last edit, NULL if never edited';

-- Note: For large-scale deployments, consider partitioning by created_at:
-- CREATE TABLE messages (...) PARTITION BY RANGE (created_at);
-- Then create monthly/weekly partitions as needed
